name: "v2ray"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NODE_VERSION: '20'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Execute PHP script
        run: php collector.php

      - name: Configure Git
        run: |
          git config --global user.email "3yed1361@gmail.com"
          git config --global user.name "3yed-61"

      - name: Commit changes
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "💡 Automatic update - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
